apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgroups.contrib.spaces.upbound.io
spec:
  group: contrib.spaces.upbound.io
  names:
    kind: XGroup
    plural: xgroups
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: Group configuration parameters.
                  properties:
                    organizationName:
                      type: string
                      description: OrganizationName is the name of the organization to which the control plane belongs
                    space:
                      type: string
                      description: Space is the name of the cloud space to which the control plane belongs
                      enum:
                        - upbound-aws-us-east-1
                        - upbound-gcp-us-west-1
                  required:
                    - organizationName
                    - space
              required:
                - parameters
