apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsharedproviders.contrib.spaces.upbound.io
spec:
  group: contrib.spaces.upbound.io
  names:
    kind: XSharedProvider
    plural: xsharedproviders
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: Shared provider configuration parameters.
                  properties:
                    controlPlaneSelector:
                      type: object
                      description: Control plane selector to match control planes by labels.
                      properties:
                        labelSelector:
                          type: array
                          description: Array of label selectors for control plane selection.
                          items:
                            type: object
                            properties:
                              matchLabels:
                                type: object
                                additionalProperties:
                                  type: string
                                description: Labels to match for control plane selection.
                    providerSpec:
                      type: array
                      description: Array of specifications of the provider packages and runtime configurations.
                      items:
                        type: object
                        properties:
                          package:
                            type: string
                            description: Package specifies the provider package.
                          runtimeConfigRef:
                            type: object
                            description: Reference to runtime configuration.
                            properties:
                              name:
                                type: string
                                description: Name of the runtime configuration reference.
                  required:
                    - controlPlaneSelector
                    - providerSpec
              required:
                - parameters
