apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: platform-ref-upbound
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/platform-ref-upbound
    meta.crossplane.io/license: Apache-2.0
spec:
  crossplane:
    version: ">=v1.15.0-0"
  dependsOn:
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      # renovate: datasource=github-releases depName=crossplane-contrib/function-patch-and-transform
      version: "v0.5.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-extra-resources
      # renovate: datasource=github-releases depName=crossplane-contrib/function-extra-resources
      version: "v0.0.3"
    - function: xpkg.upbound.io/crossplane-contrib/function-go-templating
      # renovate: datasource=github-releases depName=crossplane-contrib/function-go-templating
      version: "v0.4.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      # renovate: datasource=github-releases depName=crossplane-contrib/function-auto-ready
      version: "v0.2.1"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-kubernetes
      version: "v0.14.0-rc0.52.g5b2412e"
