apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xupboundreposets.sa.upbound.io
spec:
  compositeTypeRef:
    apiVersion: sa.upbound.io/v1
    kind: XUpboundRepoSet
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-platform-ref-upboundxupboundreposet
    step: xupboundreposet
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
