apiVersion: sa.upbound.io/v1
kind: XUpboundRepoSet
metadata:
  name: example
spec:
  parameters:
    organization: upboundcare
    permissions:
      teams:
        solutions-non-prod-ci-team:
          permission: write
    repositories:
      configuration-aws-network:
        public: true
        publish: true
      configuration-aws-network_xnetwork:
        public: true
        publish: true
    tokenSecretRef:
      name: solutions-non-prod-bootstrap-token
      namespace: default
      key: token
